name: Release Obsidian Plugin

on:
    push:
        branches:
            - main # or any other branch you use for releases

jobs:
    build-and-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # Fetches all history for tags and branches

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: Build plugin
              run: |
                  npm install
                  npm run build

            - name: Determine new tag
              run: |
                  tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
                  # Increment the tag or handle as needed here

            - name: Create release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  # Use the determined tag to create a release
